---
language: node_js
dist: xenial
os: linux
node_js: node

addons:
  apt:
    packages:
      - linkchecker

env:
  global:
    # GITHUB_TOKEN=secret
    secure: kWGaRhaQa4XFRwYWMMBlx+lsNnpf7TariGN0LEZIIsn5GhTnEbdYUDFJgnJLy4xWGF8InMEnkpcBrSKUFmAt8hSwhCy137B+G1h/sC+72QH4RK3lC+NJzDqj4QlYHwUTiXRCS/HzaiXawX5KXRj66p34uPirOGM86JORajf/+FB7X3Ry4432XNz9m3k/JPN4clAJtkAVFp0TaQ2haQPWyMqjaE1i2fzbCFgABG7TNGb+vW7cE9//s1HQ6e7q8GD/wAIWMcqGLP7UPdh5h5dGfx2FsPwgQ+3ZeVIPDfeQnLhG6EQQuqf2339QNSHCaCgBa3lTc8vqx4obZA8XXEM/yef0sEaYYC74kjeyWFTl98GB3ROlZ/uTI+QNIaCR/WI+wQvvtjRbgAOfOH3nNZ9rx9yVEAjXuNb3BSz+UmB/5t7rmo3BipvbiLaUhDAfDAUbzzRfK7UL2cQHDY0XL8XOn9nn5UzWe0WeKosqUby8lJ8qJhkdp4LO95tnl5Mr9FSeikoIavXDTD82yWS3pW5IJJRIkD8c8A89fMT3TniaGV4L022gBZelOOjILY8OMDX6tBzUIogklHJiRtaJZ3wFckKNx1O2Z4mA05vVFMpge8wN4wwY2xact8QkHjvuYMRHgamnTSoYPOF9wVCkasy2/lRbFKzYeiVrNuhd3NDOW1Y=

install:
  - npm install -g gatsby-cli
  - (cd toktok && npm install)

script:
  - (cd toktok && gatsby build)

after_success:
  - git config --global push.default simple
  - git config --global user.email "deploy@travis-ci.org"
  - git config --global user.name "Travis Deployer"
  - if [ -n "$GITHUB_TOKEN" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then make upload; fi
